// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel Mult2x2

int lx;
int z;
int intermediate;
int ry;

RWStructuredBuffer<float> left;
RWStructuredBuffer<float> right;
RWStructuredBuffer<float> output;


[numthreads(8,8,1)]
void Mult2x2(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= lx || id.y >= ry) {
		return;
	}
	output[id.x * ry + id.y] += left[id.x * intermediate + z] * right[z * ry + id.y];
}
